---
files:
  include: assets/styles/**/*.scss
rules:
  clean-import-paths: 0
  extends-before-mixins: 2
  extends-before-declarations: 2
  force-pseudo-nesting: 0
  force-element-nesting: 0
  leading-zero: 0
  placeholder-in-extend: 2
  property-sort-order: 0
  mixins-before-declarations:
  - 1
  - exclude:
    - hover
    - hoverText
    - hoverOpacity
    - mqSmallestChannel
    - mqLargestChannel
    - mqOnlyChannel
    - desktopResponsiveTitle
    - tabletResponsiveTitle
  no-color-literals: 0
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  no-url-protocols: 0
  no-url-domains: 0
  no-qualifying-elements:
  - 1
  - allow-element-with-class: true
  indentation:
  - 2
  - size: 2
  nesting-depth: 0
  class-name-format:
  - 1
  - convention: hyphenatedbem
  mixin-name-format: 0
  variable-name-format: 0
  function-name-format: 0
  quotes:
  - 1
  - style: double
